import { Router } from "express";
import passport from "passport";
import { AllNotifications, MarkNotificationsAsRead } from "../controllers/notification.controller.js";
import { checkActiveUser } from "../middleware/checkActiveUsers.js";
import { fetchCommentNotifications, markCommentNotificationsAsRead } from "../controllers/commentNotification.controller.js";
const router = Router();
router.use(passport.authenticate("jwt", { session: false }));
router.use(checkActiveUser);
router.route("/view").get(AllNotifications);
router.route("/mark-read").post(MarkNotificationsAsRead);
router.get("/comment-notifications", fetchCommentNotifications);
router.post("/comment-notifications/mark-read",markCommentNotificationsAsRead);
export default router;