import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS),

  admin: Object.values(PERMISSIONS),

  director: [
    // 🔹 Announcements
    PERMISSIONS.CREATE_ANNOUNCEMENT,
    PERMISSIONS.DELETE_ANNOUNCEMENT,
    PERMISSIONS.EDIT_ANNOUNCEMENT,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,

    // 🔹 Collective Agreements
    PERMISSIONS.CREATE_COLLECTIVE_AGREEMENT,
    PERMISSIONS.DELETE_COLLECTIVE_AGREEMENT,
    PERMISSIONS.EDIT_COLLECTIVE_AGREEMENT,
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,

    // 🔹 Emergency Contacts
    PERMISSIONS.CREATE_EMERGENCY_CONTACT,
    PERMISSIONS.DELETE_EMERGENCY_CONTACT,
    PERMISSIONS.EDIT_EMERGENCY_CONTACT,
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,

    // 🔹 Employees
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.VIEW_EMPLOYEES,

    // 🔹 Events
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.DELETE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.VIEW_EVENTS,
    PERMISSIONS.VIEW_REGISTERATIONS,

    // 🔹 Event Minutes
    PERMISSIONS.CREATE_EVENT_MINUTE,
    PERMISSIONS.DELETE_EVENT_MINUTE,
    PERMISSIONS.EDIT_EVENT_MINUTE,
    PERMISSIONS.VIEW_EVENT_MINUTES,

    // 🔹 FAQs
    PERMISSIONS.CREATE_FAQ,
    PERMISSIONS.DELETE_FAQ,
    PERMISSIONS.EDIT_FAQ,
    PERMISSIONS.VIEW_FAQS,

    // 🔹 HR Updates
    PERMISSIONS.VIEW_HR_UPDATES,

    // 🔹 Organizational Chart
    PERMISSIONS.CREATE_ORG_CHART,
    PERMISSIONS.DELETE_ORG_CHART,
    PERMISSIONS.EDIT_ORG_CHART,
    PERMISSIONS.VIEW_ORG_CHART,

    // 🔹 Program Manuals
    PERMISSIONS.CREATE_PROGRAM_MANUAL,
    PERMISSIONS.DELETE_PROGRAM_MANUAL,
    PERMISSIONS.EDIT_PROGRAM_MANUAL,
    PERMISSIONS.VIEW_PROGRAM_MANUALS,
  ],

  manager: [
    // 🔹 Announcements
    PERMISSIONS.VIEW_ANNOUNCEMENTS,

    // 🔹 Collective Agreements
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,

    // 🔹 Emergency Contacts
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,

    // 🔹 Employees
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.VIEW_EMPLOYEES,

    // 🔹 Events
    PERMISSIONS.VIEW_EVENTS,

    // 🔹 Event Minutes
    PERMISSIONS.VIEW_EVENT_MINUTES,

    // 🔹 FAQs
    PERMISSIONS.VIEW_FAQS,

    // 🔹 HR Updates
    PERMISSIONS.VIEW_HR_UPDATES,

    // 🔹 Organizational Chart
    PERMISSIONS.CREATE_ORG_CHART,
    PERMISSIONS.DELETE_ORG_CHART,
    PERMISSIONS.EDIT_ORG_CHART,
    PERMISSIONS.VIEW_ORG_CHART,

    // 🔹 Program Manuals
    PERMISSIONS.VIEW_PROGRAM_MANUALS,
  ],

  hr: [
    // 🔹 Announcements
    PERMISSIONS.CREATE_ANNOUNCEMENT,
    PERMISSIONS.DELETE_ANNOUNCEMENT,
    PERMISSIONS.EDIT_ANNOUNCEMENT,
    PERMISSIONS.VIEW_ANNOUNCEMENTS,

    // 🔹 Collective Agreements
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,

    // 🔹 Emergency Contacts
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,

    // 🔹 Employees
    PERMISSIONS.VIEW_EMPLOYEES,

    // 🔹 Events
    PERMISSIONS.VIEW_EVENTS,

    // 🔹 Event Minutes
    PERMISSIONS.VIEW_EVENT_MINUTES,

    // 🔹 FAQs
    PERMISSIONS.VIEW_FAQS,

    // 🔹 HR Updates
    PERMISSIONS.CREATE_HR_UPDATE,
    PERMISSIONS.DELETE_HR_UPDATE,
    PERMISSIONS.EDIT_HR_UPDATE,
    PERMISSIONS.VIEW_HR_UPDATES,

    // 🔹 Organizational Chart
    PERMISSIONS.VIEW_ORG_CHART,

    // 🔹 Program Manuals
    PERMISSIONS.VIEW_PROGRAM_MANUALS,
  ],

  employee: [
    // 🔹 Announcements
    PERMISSIONS.VIEW_ANNOUNCEMENTS,

    // 🔹 Collective Agreements
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,

    // 🔹 Emergency Contacts
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,

    // 🔹 Employees
    PERMISSIONS.VIEW_EMPLOYEES,

    // 🔹 Events
    PERMISSIONS.VIEW_EVENTS,

    // 🔹 Event Minutes
    PERMISSIONS.VIEW_EVENT_MINUTES,

    // 🔹 FAQs
    PERMISSIONS.VIEW_FAQS,

    // 🔹 HR Updates
    PERMISSIONS.VIEW_HR_UPDATES,

    // 🔹 Organizational Chart
    PERMISSIONS.VIEW_ORG_CHART,

    // 🔹 Program Manuals
    PERMISSIONS.VIEW_PROGRAM_MANUALS,
  ],
};
