import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS),

  volunteer_admin: Object.values(PERMISSIONS).filter((p) => {
    const excludedPermissions: string[] = [
      PERMISSIONS.EDIT_EMPLOYEE,
      PERMISSIONS.DELETE_EMPLOYEE,
      PERMISSIONS.CREATE_EMPLOYEE,
      PERMISSIONS.TICKET_CATEGORY_MANAGE,
      PERMISSIONS.EMPLOYEE_STATUS_CHANGE,
    ];

    return !excludedPermissions.includes(p);
  }),

  manager: [
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,

    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.EMPLOYEE_STATUS_CHANGE,

    PERMISSIONS.VIEW_FAQS,

    PERMISSIONS.TICKET_VIEW_SELF,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.VIEW_PROGRAM_MANUALS,
    PERMISSIONS.CREATE_PROGRAM_MANUAL,
    PERMISSIONS.EDIT_PROGRAM_MANUAL,
    PERMISSIONS.DELETE_PROGRAM_MANUAL,
  ],

  staff: [
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,
    PERMISSIONS.TASK_VIEW_SELF,
    PERMISSIONS.VIEW_FAQS,
  ],

  volunteer: [
    PERMISSIONS.VIEW_ANNOUNCEMENTS,
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,
    PERMISSIONS.VIEW_FAQS,

    PERMISSIONS.VIEW_PROGRAM_MANUALS,
    PERMISSIONS.TASK_VIEW_SELF,
    PERMISSIONS.TASK_SUBMIT,
    PERMISSIONS.TASK_REPORT_EXPORT,

    PERMISSIONS.TRAINING_CERTIFICATE_SUBMIT,
    PERMISSIONS.TRAINING_CERTIFICATE_VIEW_SELF,
  ],
};
