import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS),

  volunteer_admin: Object.values(PERMISSIONS).filter((p) => {
    return ![
      PERMISSIONS.EDIT_EMPLOYEE,
      PERMISSIONS.DELETE_EMPLOYEE,
      PERMISSIONS.CREATE_EMPLOYEE,
      PERMISSIONS.TICKET_CATEGORY_MANAGE,
      PERMISSIONS.TICKET_CATEGORY_ADD,
      PERMISSIONS.EMPLOYEE_STATUS_CHANGE,
      PERMISSIONS.LOCATION_CREATE,
      PERMISSIONS.LOCATION_DELETE,
      PERMISSIONS.LOCATION_EDIT,
      PERMISSIONS.LOCATION_VIEW,
      PERMISSIONS.TICKET_REPORT_SELF_MANAGED,

      PERMISSIONS.TICKET_REPORT_ALL,
      PERMISSIONS.CREATE_FAQ,
      PERMISSIONS.VIEW_FAQS,
      PERMISSIONS.VIEW_EMERGENCY_CONTACTS,
      PERMISSIONS.VIEW_EMPLOYEES,
      PERMISSIONS.EDIT_FAQ,
      PERMISSIONS.DELETE_FAQ,
      PERMISSIONS.CREATE_EMERGENCY_CONTACT,
      PERMISSIONS.EDIT_EMERGENCY_CONTACT,
      PERMISSIONS.DELETE_EMERGENCY_CONTACT,
      PERMISSIONS.TICKET_CREATE,
      PERMISSIONS.TICKET_VIEW_SELF,
    ].includes(p);
  }),

  manager: [
    // 🔹 Emergency Contacts
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,
    PERMISSIONS.CREATE_EMERGENCY_CONTACT,
    PERMISSIONS.EDIT_EMERGENCY_CONTACT,
    PERMISSIONS.DELETE_EMERGENCY_CONTACT,
    // 🔹 Employees
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.CREATE_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.EMPLOYEE_STATUS_CHANGE,
    PERMISSIONS.TICKET_CREATE,

    // 🔹 FAQs
    PERMISSIONS.VIEW_FAQS,
    PERMISSIONS.CREATE_FAQ,

    PERMISSIONS.EDIT_FAQ,
    PERMISSIONS.DELETE_FAQ,

    PERMISSIONS.TICKET_VIEW_SELF,
    PERMISSIONS.TICKET_REPORT_SELF_MANAGED,

    PERMISSIONS.TICKET_CATEGORY_ADD,
    // 🔹 Training Materials
    PERMISSIONS.VIEW_PROGRAM_MANUALS,
    PERMISSIONS.CREATE_PROGRAM_MANUAL,
    PERMISSIONS.EDIT_PROGRAM_MANUAL,
    PERMISSIONS.DELETE_PROGRAM_MANUAL,

    PERMISSIONS.LOCATION_CREATE,
    PERMISSIONS.LOCATION_DELETE,
    PERMISSIONS.LOCATION_EDIT,
    PERMISSIONS.LOCATION_VIEW,
  ],

  staff: [
    // 🔹 Emergency Contacts
    PERMISSIONS.VIEW_EMERGENCY_CONTACTS,
    PERMISSIONS.TICKET_CREATE,
    PERMISSIONS.TICKET_VIEW_SELF,
    // 🔹 FAQs
    PERMISSIONS.VIEW_FAQS,

    PERMISSIONS.TICKET_CATEGORY_ADD,
  ],
  volunteer: [
    // 🔹 Announcements
    PERMISSIONS.VIEW_ANNOUNCEMENTS,

    // 🔹 Collective Agreements
    PERMISSIONS.VIEW_COLLECTIVE_AGREEMENTS,

    // 🔹 Training Materials
    PERMISSIONS.VIEW_PROGRAM_MANUALS,
    PERMISSIONS.TASK_VIEW_SELF,
    PERMISSIONS.TASK_SUBMIT,
    PERMISSIONS.TASK_REPORT_EXPORT,

    PERMISSIONS.TRAINING_CERTIFICATE_SUBMIT,
    PERMISSIONS.TRAINING_CERTIFICATE_VIEW_SELF,
  ],
};
